apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./security/controller-0
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: sealed-secrets
      namespace: kube-system
